 const values = {
    ADD_TODO_ACTION :'ADD_TODO',
    REMOVE_TODO_ACTION : 'REMOVE_TODO',
    UPDATE_TODO_ACTION :'UPDATE_TODO',
    ACTIVE_FILTER : 'ACTIVE',
COMPLETED_FILTER : 'CPMPLETED',
ALL_FILTER : 'ALL'

}

export default values;

// Filter

